export enum EstadoDescripcionPedidoType {
  REGISTRADO = 'REGISTRADO',
  EVALUACION = 'EVALUACIÓN',
  ATENDIDO = 'ATENDIDO',
  DERIVADO = 'DERIVADO',
  REMITIDO = 'REMITIDO',
  RESPUESTA_EXTERNA_INTERNA = 'RESPUESTA_EXTERNA_INTERNA',
  NO_PROCEDE = 'NO_PROCEDE',
  DEVUELTO = 'DEVUELTO'
};
